# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c14c31781a6bf5c65a32c7b4496edcf234d2d92b9aeb51de8e49171972de25e13c3d1d60feb0f1b85ea5f67d579e7509195882ce093e4e0fdd26e05d5e4bddf2

test:
  secret_key_base: 5b9eb893068edfa06bc561530de250bf7cfd317a6ca6ee15b62c264250976e339d814b2f66c186aea9c8de2bbd4af18aade7fd019dcbeab004434654fdc6b0dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
